# Site settings
title: btko's site
url: 'http://github.io/bbttko'
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-leap-day

# Build Settings
markdown: kramdown